/*WHICH GENRE HAS THE BEST AVERAGE RATING*/
SELECT AVG(RATING)AS AVGRATE,GENRES
FROM googleplaystore
WHERE RATING IS NOT NULL AND REVIEWS >100000
GROUP BY GENRES
ORDER BY AVGRATE DESC

/*THE MOST INSTALLED APPS WITH PRICE ABOVE 50 $*/
SELECT G.APP,P.INSTALLS,P.PRICE
FROM googleplaystore  G
JOIN googleplaystoreprice  P
 ON G.APP=P.APP 
 WHERE P.PRICE>=50
ORDER BY P.INSTALLS DESC

/*AVERAGE PRICE FOR EACH GENRES*/
SELECT GENRES,AVG(P.PRICE) AS AVGPRICE
FROM googleplaystore  G
JOIN googleplaystoreprice  P
 ON G.APP=P.APP 
GROUP BY GENRES
ORDER BY AVGPRICE DESC


/*TOTALLY FREE GENRES WITH THE MOST NUMBER OF APPS*/
WITH CTEPRICE AS
(
SELECT G.GENRES,SUM(P.PRICE)/COUNT(G.APP) AS PRICEPERAPP,COUNT(G.APP)AS APPNUMS
FROM googleplaystore  G
JOIN googleplaystoreprice  P
 ON G.APP=P.APP 
GROUP BY G.GENRES
)
SELECT GENRES,PRICEPERAPP, APPNUMS
FROM CTEPRICE
WHERE PRICEPERAPP=0
ORDER BY APPNUMS DESC
